version: '3.2'
services:
  product-db:
    hostname: product-db
    build:
      context: ./
      dockerfile: docker/DockerfileProductDB
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    networks:
      backend:
        aliases:
          - product-db

  product-ms:
    build:
      context: ./
      dockerfile: docker/DockerfileProductMS
    ports:
      - "8081:8081"
    depends_on:
      - product-db
    networks:
      - backend


networks:
  backend:
    driver: bridge
