apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: distributed-systems-product
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              name: product-port

---
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  type: ClusterIP  # Change this to LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      name: product-port
  selector:
    app: product
