version: '3.2'
services:
  category-db:
    hostname: category-db
    build:
      context: ./
      dockerfile: docker/CategoryDatabase
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    networks:
      backend:
        aliases:
          - category-db

  category-service:
    build:
      context: ./
      dockerfile: docker/CategoryService
    ports:
      - "8080:8080"
    depends_on:
      - category-db
    networks:
      - backend


networks:
  backend:
    driver: bridge
